
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author E-rinGZ
 */
public class adminUpdate extends javax.swing.JFrame {

    /**
     * Creates new form adminUpdate
     */
    Connection myConnection = null;
        Statement myStatement= null;
        ResultSet myResult =null;
    public adminUpdate() {
        initComponents();
        edit1.setBackground(new Color(0,0,0,0));
        edit2.setBackground(new Color(0,0,0,0));
        edit3.setBackground(new Color(0,0,0,0));
        edit4.setBackground(new Color(0,0,0,0));
    }
    public void connect(){
        try{
            myConnection = DriverManager.getConnection("jdbc:mysql://localhost:3306/temporaryid", "root", "");
            myStatement = myConnection.createStatement();
            myResult = myStatement.executeQuery("Select * From administrator");
        }catch (SQLException e){
            e.printStackTrace();
        }
           
          
    }
    public adminUpdate(String son) {
        initComponents();
        connect();
        idnum.hide();
        namepanel.hide();
        edit1.setBackground(new Color(0,0,0,0));
        edit2.setBackground(new Color(0,0,0,0));
        edit3.setBackground(new Color(0,0,0,0));
        edit4.setBackground(new Color(0,0,0,0));
        idnum.setText(son);
        String ako = idnum.getText();
        System.out.println("testing"+ako);
         try{
            String me = "select * from administrator where id='"+ako+"'";
            Statement add = myConnection.createStatement();
            ResultSet rs = add.executeQuery(me);
            if(rs.next()){
                String lastname = rs.getString(2);
                String firstname = rs.getString(3);
                String middlename = rs.getString(4);
                String email = rs.getString(5);
                String password = rs.getString(6);
                String contact = rs.getString(7);
                String fullname = firstname+" " + middlename+ " " + lastname;
                name.setText(fullname);
                eadd.setText(email);
                con.setText(contact);
                
                
                
                
                
                
            }
        }catch (SQLException e){
            e.printStackTrace();
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namepanel = new javax.swing.JPanel();
        apelido = new javax.swing.JTextField();
        pangalan = new javax.swing.JTextField();
        gitna = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        idnum = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pass = new javax.swing.JLabel();
        con = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        eadd = new javax.swing.JLabel();
        edit4 = new javax.swing.JButton();
        edit3 = new javax.swing.JButton();
        edit2 = new javax.swing.JButton();
        edit1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namepanel.setBackground(new java.awt.Color(252, 255, 254));
        namepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        apelido.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        apelido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 20, 73), 2, true));
        apelido.setMargin(new java.awt.Insets(100, 100, 100, 100));
        namepanel.add(apelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 390, 40));

        pangalan.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        pangalan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 20, 73), 2, true));
        namepanel.add(pangalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 390, 40));

        gitna.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        gitna.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 20, 73), 2, true));
        namepanel.add(gitna, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 390, 40));

        cancel.setBackground(new java.awt.Color(255, 102, 102));
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        namepanel.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 150, 30));

        save.setBackground(new java.awt.Color(61, 83, 244));
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        namepanel.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 170, 40));

        getContentPane().add(namepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 460, 350));

        jPanel1.setBackground(new java.awt.Color(226, 242, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(61, 83, 244));
        jButton1.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("UPDATE");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 270, 50));

        idnum.setText("jLabel1");
        jPanel1.add(idnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 170, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 88, 670, 30));

        pass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pass.setText(" CURRENT PASSWORD");
        pass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 460, 50));

        con.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        con.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        con.setText(" CONTACT");
        con.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(con, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 460, 50));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN UPDATE");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 480, 70));

        name.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText(" FULLNAME");
        name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 460, 50));

        eadd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        eadd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eadd.setText(" EMAIL ADDRESS");
        eadd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(eadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 460, 50));

        edit4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahe/1x/1x/pen40Asset 3.png"))); // NOI18N
        edit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                edit4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                edit4MouseExited(evt);
            }
        });
        jPanel1.add(edit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 70, 50));

        edit3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahe/1x/1x/pen40Asset 3.png"))); // NOI18N
        edit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                edit3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                edit3MouseExited(evt);
            }
        });
        jPanel1.add(edit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 70, 50));

        edit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahe/1x/1x/pen40Asset 3.png"))); // NOI18N
        edit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                edit2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                edit2MouseExited(evt);
            }
        });
        jPanel1.add(edit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 70, 50));

        edit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahe/1x/1x/pen40Asset 3.png"))); // NOI18N
        edit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                edit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                edit1MouseExited(evt);
            }
        });
        edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit1ActionPerformed(evt);
            }
        });
        jPanel1.add(edit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 70, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahe/green1kAsset 1.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 690, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit1MouseEntered
        edit1.setBackground(Color.white);
    }//GEN-LAST:event_edit1MouseEntered

    private void edit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit1MouseExited
        edit1.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_edit1MouseExited

    private void edit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit2MouseEntered
        edit2.setBackground(Color.white);
    }//GEN-LAST:event_edit2MouseEntered

    private void edit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit2MouseExited
        edit2.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_edit2MouseExited

    private void edit3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit3MouseEntered
        edit3.setBackground(Color.white);
    }//GEN-LAST:event_edit3MouseEntered

    private void edit3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit3MouseExited
        edit3.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_edit3MouseExited

    private void edit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_edit4MouseClicked

    private void edit4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit4MouseEntered
        edit4.setBackground(Color.white);
    }//GEN-LAST:event_edit4MouseEntered

    private void edit4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit4MouseExited
        edit4.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_edit4MouseExited

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
       String ap = apelido.getText();
       String pa = pangalan.getText();
       String gi = gitna.getText();
       String y = idnum.getText();
       try{
         System.out.println(y);
         String sql  = "update administrator set lastname = '"+ap+"'"+", firstname = '"+pa+"'"+", middlename = '"+gi+"'"+" where id = '"+y;
         Statement update = myConnection.createStatement();
         update.executeUpdate(sql);
         
         namepanel.hide();
         edit1.show();
         edit2.show();
         edit3.show();
         edit4.show();
        
        
       }catch (SQLException e){
           e.printStackTrace();
       }
       connect();
    }//GEN-LAST:event_saveActionPerformed

    private void edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit1ActionPerformed
        edit1.hide();
        edit2.hide();
        edit3.hide();
        edit4.hide();
        namepanel.show();
    }//GEN-LAST:event_edit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apelido;
    private javax.swing.JLabel background;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel con;
    private javax.swing.JLabel eadd;
    private javax.swing.JButton edit1;
    private javax.swing.JButton edit2;
    private javax.swing.JButton edit3;
    private javax.swing.JButton edit4;
    private javax.swing.JTextField gitna;
    public static javax.swing.JLabel idnum;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel name;
    private javax.swing.JPanel namepanel;
    private javax.swing.JTextField pangalan;
    private javax.swing.JLabel pass;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
