
import java.awt.event.KeyEvent;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Set;
import javax.swing.JOptionPane;
import java.sql.ResultSetMetaData;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author E-rinGZ
 */
public class adminRegister extends javax.swing.JFrame {

    /**
     * Creates new form adminRegister
     */
     Connection myConnection = null;
        Statement myStatement= null;
        ResultSet myResult =null;
    public adminRegister() {
        initComponents();
        connect();
        
    }
    public void connect(){
        try{
            myConnection = DriverManager.getConnection("jdbc:derby://localhost:1527/admindatabase", "admindatabase", "admin");
            myStatement = myConnection.createStatement();
            myResult =myStatement.executeQuery("SELECT * FROM admindatabase.admininfo");
        }catch(SQLException e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        cellphone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        confirmapassword = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(226, 242, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN REGISTRATION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 261, 44));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("NAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 61, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CELLPHONE #");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 114, 42));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("CONFIRM PASSWORD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, 34));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 420, 30));

        cellphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellphoneActionPerformed(evt);
            }
        });
        cellphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cellphoneKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cellphoneKeyTyped(evt);
            }
        });
        jPanel1.add(cellphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 370, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("EMAIL ADDRESS: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 34));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("PASSWORD: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 34));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 350, 30));

        confirm.setText("CONFIRM");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        jPanel1.add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 110, 30));

        cancel.setText("CANCEL");
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 30));

        confirmapassword.setText("jPasswordField1");
        jPanel1.add(confirmapassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 310, 30));

        password.setText("jPasswordField1");
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 390, 30));

        background.setBackground(new java.awt.Color(226, 242, 240));
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cellphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cellphoneActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here: 
        int answer;
         answer = JOptionPane.showConfirmDialog(null, "Are you sure you want to continue?", "CONFIRMATION", JOptionPane.YES_NO_OPTION);
         if(answer == 0){
             String pangalan = name.getText();
             String pass = password.getText();
             String confirmpass = confirmapassword.getText();
             String cp = cellphone.getText();
             String admin = username.getText();
             int namelength = pangalan.length();
             int passlength = pass.length();
             int confirmlength = confirmpass.length();
             int cplength = cp.length();
             int adminlength = admin.length();
             //int cell = Integer.parseInt(cp.trim());
             if(namelength == 0 || passlength == 0 || confirmlength==0 ||cplength==0 ||adminlength == 0 ){
             JOptionPane.showMessageDialog(null,"Please Fill up all requirements needed.","ERROR MESSAGE",JOptionPane.ERROR_MESSAGE);
         }else{
               try{
                   PreparedStatement put = myConnection.prepareStatement("insert into admindatabase.admininfo values(?,?,?,?)" );
                   put.setString(1, admin);
                   put.setString(2, pangalan);
                   put.setString(3, pass);
                   put.setString(4, cp);
                    int row = put.executeUpdate();
                   JOptionPane.showMessageDialog(null, "LOG IN SUCCESSFULLY!!");
                   myConnection.close();
                   this.dispose();
                  // new adminLogIN().setVisible(true);
                   new adminLogIN().show();
               }catch(SQLException e){
                    e.printStackTrace();          
               }
             }
             
         }
    }//GEN-LAST:event_confirmActionPerformed

    private void cellphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cellphoneKeyPressed
        // limit the integer in 11 digits only
        String cpnumber = cellphone.getText();
        int length = cpnumber.length();
     if(length<11)
            if(length<11){
                cellphone.setEditable(true);
            }else{
                cellphone.setEditable(false);
            
            }else{
              if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE|| evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ) {
                    cellphone.setEditable(true);                  
                    }else{
                    cellphone.setEditable(false);
                    }
              } 
    }//GEN-LAST:event_cellphoneKeyPressed

    private void cellphoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cellphoneKeyTyped
        // input should be numbers only
        char c = evt.getKeyChar();
        String cpText = cellphone.getText();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_cellphoneKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField cellphone;
    private javax.swing.JButton confirm;
    private javax.swing.JPasswordField confirmapassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
