
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author E-rinGZ
 */
public class practice1 extends javax.swing.JFrame {

    /**
     * Creates new form practice1
     */
    Connection myConnection=null;
    Statement myStatement=null;
    ResultSet myResult=null;

    public practice1() {
        initComponents();
        connect();
        petsaPakita();
        orasPakita();
      

        
       
        String ako = "SELECT MAX(idnumber) FROM ron.infoko";
                try {
                    Statement add = myConnection.createStatement();
                 ResultSet rs = add.executeQuery(ako);
                 if (rs.next()){
                     String id = rs.getString(1);
                     System.out.println(id);
                     
                     StringBuffer buff = new StringBuffer(id);
                     buff.delete(0, 4);
                     String a = buff.toString();
                     int b = Integer.parseInt(a);
                     int c = b + 1;
                    String d = String.valueOf(c);
                    String e = "CDM-"+c;
                    idnumber.setText(e);
                     
                 }
             } catch (SQLException ex1) {
                 Logger.getLogger(practice1.class.getName()).log(Level.SEVERE, null, ex1);  
                 
                
             }
         
                
    }
    public void petsaPakita(){
        SimpleDateFormat style = new SimpleDateFormat("MMM dd yyyy");
        Date petsa = new Date();
        date.setText(style.format(petsa));
    }
    public void orasPakita(){
        new Timer(0, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");
                Date datenow = new Date();
                oras.setText(format.format(datenow));
            }    
    }).start();
    }
    void connect(){
           try{
            myConnection = DriverManager.getConnection("jdbc:derby://localhost:1527/practice", "ron", "ron");
            myStatement = myConnection.createStatement();
            myResult = myStatement.executeQuery("SELECT * FROM ron.infoko");
            
        }catch(SQLException e){
            e.printStackTrace();
        }
       
    }

     public ImageIcon resizeImage(String ImagePath){
        ImageIcon MyImage = new ImageIcon(ImagePath); 
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(photo.getWidth(), photo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
     }
     
      


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idnumber = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        oras = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();
        change = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idnumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idnumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idnumber.setText("CDM-2100001");

        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setText("PETSA");

        confirm.setText("CONFIRM");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        oras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oras.setText("jLabel1");

        photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahe/editAsset 1.png"))); // NOI18N

        change.setText("CHANGE");
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(idnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oras, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(oras, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(change)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
       
         String idno = idnumber.getText();
            Date date = new Date();
            java.sql.Date dql =new java.sql.Date(date.getDate());
            Date time = new Date();
            java.sql.Date tql =new java.sql.Date(date.getDate());
          String pic = photo.getName().toString();
           System.out.println(pic);
           
            
       
        try {
            PreparedStatement  put = myConnection.prepareStatement("insert into ron.infoko values(?,?,?,?)");
            put.setString(1,idno);
            put.setDate(2, dql);
            put.setDate(3, dql);
             try {
                
                 //FileInputStream fis = new FileInputStream("C:\\Users\\E-rinGZ\\OneDrive\\Desktop\\image\\schoool uniform.jpg");
                 FileInputStream fis = new FileInputStream(pic);
                try {
                    put.setBinaryStream(4, fis,fis.available());
                } catch (IOException ex) {
                    Logger.getLogger(practice1.class.getName()).log(Level.SEVERE, null, ex);
                }
             } catch (FileNotFoundException ex) {
                 Logger.getLogger(practice1.class.getName()).log(Level.SEVERE, null, ex);
             }     
            int row = put.executeUpdate();
            myConnection.close();
            JOptionPane.showMessageDialog(this, "Registered");  
            
            
       
        } catch (SQLException ex) {
            Logger.getLogger(practice1.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Naulit ang id");         
        }
                this.dispose();
                new ensayo().show();          
    }//GEN-LAST:event_confirmActionPerformed

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images","jpg", "gif", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        
        
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            photo.setIcon(resizeImage(path));
            photo.setName(path);
            
        }else if(result== JFileChooser.CANCEL_OPTION){
            JOptionPane.showMessageDialog(null,"DI KA PUMILI","ERROR MESSAGE",JOptionPane.ERROR_MESSAGE);
            
        }
      
    }//GEN-LAST:event_changeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(practice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(practice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(practice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(practice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new practice1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton change;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel date;
    private javax.swing.JLabel idnumber;
    private javax.swing.JLabel oras;
    private javax.swing.JLabel photo;
    // End of variables declaration//GEN-END:variables
}
