
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author E-rinGZ
 */


public class studentList extends javax.swing.JFrame {

    /**
     * Creates new form studentList
     */
    Connection myConnection = null;
    Statement myStatement = null;
    ResultSet myResult = null;
    public studentList() {
        initComponents();
        showUser();
    }
    public ArrayList<User> userlist(){
        ArrayList<User> usersList = new ArrayList<>();
        try{
        myConnection = DriverManager.getConnection("jdbc:derby://localhost:1527/studentdata", "student", "admin");
        myStatement = myConnection.createStatement();
        myResult = myStatement.executeQuery("Select * From student.data");
        //table.setModel(DbUtils.resultSetToTableModel(myResult));
        User user;
        while(myResult.next()){
            user= new User(myResult.getString("idnumber"), myResult.getString("studentnumber"), myResult.getString("lastname"),myResult.getString("firstname"), myResult.getString("middlename"), myResult.getString("course"), myResult.getString("cellphone"), myResult.getString("email"));
            usersList.add(user);
        }
        }catch (SQLException e){
            e.printStackTrace();
        }
        
            return usersList;
    }
    public void showUser(){
        ArrayList<User> list = userlist();
        DefaultTableModel model = (DefaultTableModel) tableta.getModel();
        Object[] row = new Object[8]; 
        for (int i = 0 ; i<list.size() ; i++){
            row[0] = list.get(i).getidnumber();
            
            row[1] = list.get(i).getstudentnumber();         
            row[2] = list.get(i).getlastname()+ " " + list.get(i).getfirstname()+ " " + list.get(i).getmiddlename();            
            row[3] = list.get(i).getcourse();       
            row[4] = list.get(i).getcellphone();
            row[5] = list.get(i).getemail();   
            model.addRow(row);
        }        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        searchtype = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(searchtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 230, 31));

        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 100, 30));

        tableta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID #", "STUDENT #", "NAME", "COURSE", "CELLPHONE #", "EMAIL ADDRESS"
            }
        ));
        tableta.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tableta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 920, 90));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STUDENT INFORMATION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 890, 40));

        ok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel1.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, 130, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("CANCEL");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 130, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("NEW");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 130, 30));
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 937, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new studentReg().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Are you sure you want to continue?", "CONFIRMATION", JOptionPane.YES_NO_OPTION);
        idOutput input = new idOutput();
        DefaultTableModel mod = (DefaultTableModel) tableta.getModel();
        int selecta = tableta.getSelectedRow();
         input.studentn.setText( mod.getValueAt(selecta, 1).toString());
        //String info = input.idnumber.getText();
        String info = mod.getValueAt(selecta, 1).toString();
        // idOutput.cdm.setText(get);
       // System.out.println(info);     
        this.hide();
        new idOutput(info).show(); 
    }//GEN-LAST:event_okActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        
        String sql = "SELECT ALL FROM student.data"+searchtype.getText();     
        try {
            // TODO add your handling code here:
            myConnection = DriverManager.getConnection("jdbc:derby://localhost:1527/studentdata", "student", "admin");
            myStatement = myConnection.createStatement();
            myResult = myStatement.executeQuery(sql);
            if(myResult.next()){
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(studentList.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
      
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JButton ok;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchtype;
    public static javax.swing.JTable tableta;
    // End of variables declaration//GEN-END:variables
}
